### ISSUE TITLE
1.0.3 does not install include dirs

### ISSUE THREAD

**Issue by alex-tee** [lsp-plugins/lsp-dsp-lib#17]
Looks like `make install` does not install the include dirs

**Comment by alex-tee** [comment]
actually it looks like they are not installed since 1.0.0

0.5.14 is the last release that installs the include dirs

**Comment by alex-tee** [comment]
Thanks, I think this should be on by default though. Every single library installs its headers when you run the install command with make/meson/cmake/waf/etc.

**Comment by sadko4u** [comment]
Just released 1.0.4 version with updated build scripts.
Now should be fine for you.
Please verify.

https://github.com/lsp-plugins/lsp-dsp-lib/releases/tag/1.0.4

**Comment by alex-tee** [comment]
it works, thanks!!
