### ISSUE TITLE
[LSP_COMMON_LIB] Error 128

### ISSUE THREAD

**Issue by erickingxu** [lsp-plugins/lsp-dsp-lib#18]
when I run  comandline as :make fetch              
I got some error, cannot pull right lsp common lib.
            
Fetching desired source code dependencies
Cloning  ->  [devel]
fatal: The empty string is not a valid path
make[1]: *** [LSP_COMMON_LIB] Error 128
make: *** [fetch] Error 2

**Comment by sadko4u** [comment]
You need to run `make config` before running `make fetch`.
